config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users 
  resources :sessions, only: [:new, :create, :destroy] 

  get '/about' =>'static_pages#about'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :email, :case_sensitive => false 
  has_secure_password
  validates :password, length: { minimum: 6 }

  #this helps keep a user logged in until they logout even if they close the browser.
  #this stores a hash digest in the database of 16 charaters (64 combination 64 base64)
  #this allows to signin a user with  by retrieving a token from the cookie, calculating 
  #the hash digest and searching for the remember token matching the digests value.
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token) 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # session[:user] = user.id
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' #Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  def new
    @user = User.new
  end

  def index
    # @users = User.all
    # @user = User.find(params[:id])
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def create
    @user = User.new(user_params)
      # if @user.save
      #   sign_in @user
      #   redirect_to @user, :notice => "Welcome to Shopping Obsession"  #this may need to redirect to the index page
      # else
      #   render 'new'
      # end
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'Welcome to Shopping Obsession.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])    
  end

  def update
    @user = User.find(params[:id])  
    if @user.update_attributes(user_params)
      redirect_to @user, :notice => "Profile updated"  #this may need to redirect to the index page
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @user.to_json }
    end
    # render :json => @user.to_json
  end


  private

    def user_params
      params.require(:user).permit(:username, :email, :shoe_size, :dress_size, :top_size, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in." 
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to) 
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapper-head">
    <h6>Built by <a href="http://twitter.com/sashaydoll" target="_blank">Denine Guy</a> using the Gilt Groupe API</h6>
    <h6>(no affiliation with <a href="http://gilt.com" target="_blank">Gilt Groupe</a>)</h6>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="wrapper-head">
      <p><%= link_to "Shopping Obsession", root_path, id: "logo" %></p>
      <!-- <p><%#= link_to "Browse Product Just For You", root_path, id: "logo" %></p> -->
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "About", about_path%></li>
          <li><%= link_to "My Feed", current_user %></li>
          <li><%= link_to "All Women's", "#" %></li>
          <% if signed_in? %>
            <!-- <li><%#= link_to "Users", "#" %></li> -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiltRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta charset=utf-8>
  <meta name="keywords" content="fashion"/>
  <meta name="description" content="My Shopping Obsession">
  <title>My Shopping Obsession</title>
  <!-- <link rel="icon" type="image/jpg" href="favicon.jpg" /> -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->   
  <%= analytics_init if Rails.env.production? %>  
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container" >
    <!-- <p class="alert-success alert-error"><%#= flash[:notice] %></p> -->
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%=value%></div>
    <% end %>
    <%= yield %>
    <%#= debug(params) if Rails.env.development? %> 
  </div>
  <%= render 'layouts/footer' %>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <%#= javascript_include_tag 'shoes_app' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
  <div id="welcome-page">
    <!-- <ul class="home-page-hero"> -->
      
    <!-- </ul> -->
  </div>
  <div>
    <!-- <h1>StaticPages#home</h1> -->
    <!-- <p>Find me in app/views/static_pages/home.html.erb</p> -->
  </div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-error">
            This form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li>* <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :username,"Username:" %></br>
        <%= f.text_field :username %></br>
      </p>

      <p>
        <%= f.label :email,"Email:" %></br>
        <%= f.text_field :email %></br>
      </p>

      <p>
        <%= f.label :password %></br>
        <%= f.password_field :password %></br>
      </p>

      <p>
        <%= f.label :password_confirmation, "Confirm Password:" %></br>
        <%= f.password_field :password_confirmation %></br>
      </p>

      <p>
        <%= f.label :shoe_size %>:</br>
        <%= f.select :shoe_size, [ '4', '4.5', '5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9'                        , '9.5', '10', '10.5', '11', '11.5', '12', '12.5', '13', '13.5',                        '14', '14.5', '15' ], :prompt => 'Select One' %></br>
      </p>

      <!-- TODO: figure out what I want to group together and then make sure I add those fields to the model -->
      <p>
        <%= f.label :dress_size %>:</br>
        <%= f.select :dress_size, [ '00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18',
                                    '20', '22', '24', '26', '28', 'one size'], :prompt => 'Select One' %></br>
      </p>

      <p>
        <%= f.label :top_size %>:</br>
        <%= f.select :top_size, [ '00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18','20'                        , '22', '24', '26', '28', 'one size'], :prompt => 'Select One'                        %></br>
      </p>


      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%#= will_paginate %>


<ul class="users">
  <% @users.each do |user| %>
    <li>
      Username: <%= user.username %><br>
      Email: <%= user.email %>
    </li>
  <% end %>
</ul>

  

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div>
  <div>
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-error">
            This form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li>* <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :username,"Username:" %></br>
        <%= f.text_field :username %></br>
      </p>

      <p>
        <%= f.label :email,"Email:" %></br>
        <%= f.text_field :email %></br>
      </p>

      <p>
        <%= f.label :password %></br>
        <%= f.password_field :password %></br>
      </p>

      <p>
        <%= f.label :password_confirmation,"Confirm Password:" %></br>
        <%= f.password_field :password_confirmation %></br>
      </p>

      <p>
        <%= f.label :shoe_size %>:</br>
        <%= f.select :shoe_size, [ '4', '4.5', '5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '12.5', '13', '13.5', 
                                '14', '14.5', '15' ], :prompt => 'Select One' %></br>
      </p>
      <!-- TODO: figure out what I want to group together and then make sure I add those fields to the model -->
      <p>
        <%= f.label :dress_size %>:</br>
        <%= f.select :dress_size, [ '00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24', '26', '28', 'one size'], :prompt => 'Select One' %></br>
      </p>

      <p>
        <%= f.label :top_size %>:</br>
        <%= f.select :top_size, [ '00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24', '26', '28', 'one size'], :prompt => 'Select One' %></br>
      </p>

      <p><%= f.submit "Create my account" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.username) %>
<div class="wrapper">
  <div class = "row">
    <aside class="span4">
      <section>
        <h1><%= @user.username %></h1>
        
      </section>
    </aside>
  </div>

  <%#= javascript_tag "var userShoeSize = #{@user.shoe_size};" %>
  <h1>Shoes</h1>
  <div class="products-container wrapper">
      <!-- <ul class="products-container"></ul>  -->
  </div>
  <h1>Dresses</h1>
  <div class="dress-container wrapper">
      <!-- <ul class="products-container"></ul>  -->
  </div>
  <h1>Tops</h1>
  <div class="top-container wrapper">
      <!-- <ul class="products-container"></ul>  -->
  </div>
</div>
<%= javascript_tag "var userId = #{@user.id};" %>